In [17]:
import pandas as pd
df = pd.read_excel("../data/raw/Online Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df.shape

(541909, 8)

## Exploración inicial

El dataset contiene 541.909 registros y 8 variables.

Valores faltantes en las columnas Description y CustomerID.

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [27]:
df.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(5268)

In [34]:
df[df.duplicated()].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom

In [36]:
df[df.duplicated(keep=False)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

Investigamos con "InvoiceNo" los # de facturas repetidos

In [41]:
df[df.duplicated(keep=False)]["InvoiceNo"].value_counts().head(10)

InvoiceNo
547651    57
579458    53
577482    52
572103    50
574481    49
552285    48
537781    47
555524    40
569897    40
575117    40
Name: count, dtype: int64

Vamos a investigar la primera factura, ya que es importante determinar el motivo de tantos duplicados

In [43]:
df[df["InvoiceNo"] == 547651]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
131911,547651,84795B,SUNSET CHECK HAMMOCK,1,2011-03-24 12:11:00,7.95,16904.0,United Kingdom
131912,547651,21922,UNION STRIPE WITH FRINGE HAMMOCK,1,2011-03-24 12:11:00,7.95,16904.0,United Kingdom
131913,547651,82613A,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131914,547651,82613B,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131915,547651,82613C,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
...,...,...,...,...,...,...,...,...
132020,547651,85175,CACTI T-LIGHT CANDLES,32,2011-03-24 12:11:00,0.42,16904.0,United Kingdom
132021,547651,22968,ROSE COTTAGE KEEPSAKE BOX,1,2011-03-24 12:11:00,9.95,16904.0,United Kingdom
132022,547651,22501,PICNIC BASKET WICKER LARGE,1,2011-03-24 12:11:00,9.95,16904.0,United Kingdom
132023,547651,22782,SET 3 WICKER STORAGE BASKETS,1,2011-03-24 12:11:00,24.95,16904.0,United Kingdom
132024,547651,22444,GROW YOUR OWN PLANT IN A CAN,48,2011-03-24 12:11:00,1.25,16904.0,United Kingdom

In [44]:
df[df["InvoiceNo"] == 547651].duplicated().sum()

np.int64(31)

In [ ]:
df[df["InvoiceNo"] == 547651].duplicated()

131911    False
131912    False
131913    False
131914    False
131915    False
          ...
132020    False
132021    False
132022    False
132023    False
132024    False
Length: 114, dtype: bool

In [ ]:
factura = df[df["InvoiceNo"] == 547651]
factura[factura.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
131917,547651,82613A,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131918,547651,82613C,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131919,547651,82613D,METAL SIGN CUPCAKE SINGLE HOOK,1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131920,547651,82613B,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131927,547651,22084,PAPER CHAIN KIT EMPIRE,1,2011-03-24 12:11:00,2.95,16904.0,United Kingdom
131931,547651,21389,IVORY HANGING DECORATION BIRD,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131944,547651,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,1,2011-03-24 12:11:00,2.10,16904.0,United Kingdom
131955,547651,22554,PLASTERS IN TIN WOODLAND ANIMALS,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131957,547651,22551,PLASTERS IN TIN SPACEBOY,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131960,547651,22553,PLASTERS IN TIN SKULLS,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131961,547651,22556,PLASTERS IN TIN CIRCUS PARADE,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131962,547651,22555,PLASTERS IN TIN STRONGMAN,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131974,547651,85014B,RED RETROSPOT UMBRELLA,1,2011-03-24 12:11:00,5.95,16904.0,United Kingdom
131975,547651,15056P,EDWARDIAN PARASOL PINK,1,2011-03-24 12:11:00,5.95,16904.0,United Kingdom
131979,547651,22291,HANGING CHICK CREAM DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131980,547651,22292,HANGING CHICK YELLOW DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131984,547651,22293,HANGING CHICK GREEN DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131986,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131987,547651,22292,HANGING CHICK YELLOW DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131988,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131990,547651,22287,"DECORATION , WOBBLY CHICKEN, METAL",1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131991,547651,22291,HANGING CHICK CREAM DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131992,547651,22248,DECORATION PINK CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131996,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131997,547651,22288,HANGING METAL RABBIT DECORATION,1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131998,547651,22595,GINGHAM HEART DECORATION,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131999,547651,85203,HANGING WOOD AND FELT BUTTERFLY,1,2011-03-24 12:11:00,0.42,16904.0,United Kingdom
132000,547651,84457,SET/3 RABBITS FLOWER SKIPPPING ROPE,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
132001,547651,22293,HANGING CHICK GREEN DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
132003,547651,22285,HANGING HEN ON NEST DECORATION,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
132019,547651,22431,WATERING CAN BLUE ELEPHANT,1,2011-03-24 12:11:00,1.95,16904.0,United Kingdom

In [50]:
factura = df[df["InvoiceNo"] == 547651]
factura[factura.duplicated(keep=False)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
131913,547651,82613A,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131914,547651,82613B,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131915,547651,82613C,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131916,547651,82613D,METAL SIGN CUPCAKE SINGLE HOOK,1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131917,547651,82613A,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131918,547651,82613C,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131919,547651,82613D,METAL SIGN CUPCAKE SINGLE HOOK,1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131920,547651,82613B,"METAL SIGN,CUPCAKE SINGLE HOOK",1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131922,547651,22084,PAPER CHAIN KIT EMPIRE,1,2011-03-24 12:11:00,2.95,16904.0,United Kingdom
131923,547651,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,1,2011-03-24 12:11:00,2.10,16904.0,United Kingdom
131927,547651,22084,PAPER CHAIN KIT EMPIRE,1,2011-03-24 12:11:00,2.95,16904.0,United Kingdom
131930,547651,21389,IVORY HANGING DECORATION BIRD,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131931,547651,21389,IVORY HANGING DECORATION BIRD,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131932,547651,22293,HANGING CHICK GREEN DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131935,547651,22291,HANGING CHICK CREAM DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131936,547651,22292,HANGING CHICK YELLOW DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131940,547651,22287,"DECORATION , WOBBLY CHICKEN, METAL",1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131942,547651,22285,HANGING HEN ON NEST DECORATION,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131943,547651,85203,HANGING WOOD AND FELT BUTTERFLY,1,2011-03-24 12:11:00,0.42,16904.0,United Kingdom
131944,547651,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,1,2011-03-24 12:11:00,2.10,16904.0,United Kingdom
131949,547651,85014B,RED RETROSPOT UMBRELLA,1,2011-03-24 12:11:00,5.95,16904.0,United Kingdom
131953,547651,22553,PLASTERS IN TIN SKULLS,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131954,547651,22554,PLASTERS IN TIN WOODLAND ANIMALS,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131955,547651,22554,PLASTERS IN TIN WOODLAND ANIMALS,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131956,547651,22551,PLASTERS IN TIN SPACEBOY,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131957,547651,22551,PLASTERS IN TIN SPACEBOY,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131958,547651,22555,PLASTERS IN TIN STRONGMAN,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131959,547651,22556,PLASTERS IN TIN CIRCUS PARADE,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131960,547651,22553,PLASTERS IN TIN SKULLS,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131961,547651,22556,PLASTERS IN TIN CIRCUS PARADE,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131962,547651,22555,PLASTERS IN TIN STRONGMAN,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131973,547651,15056P,EDWARDIAN PARASOL PINK,1,2011-03-24 12:11:00,5.95,16904.0,United Kingdom
131974,547651,85014B,RED RETROSPOT UMBRELLA,1,2011-03-24 12:11:00,5.95,16904.0,United Kingdom
131975,547651,15056P,EDWARDIAN PARASOL PINK,1,2011-03-24 12:11:00,5.95,16904.0,United Kingdom
131979,547651,22291,HANGING CHICK CREAM DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131980,547651,22292,HANGING CHICK YELLOW DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131982,547651,84457,SET/3 RABBITS FLOWER SKIPPPING ROPE,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131983,547651,22248,DECORATION PINK CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131984,547651,22293,HANGING CHICK GREEN DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131985,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131986,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131987,547651,22292,HANGING CHICK YELLOW DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131988,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131989,547651,22288,HANGING METAL RABBIT DECORATION,1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131990,547651,22287,"DECORATION , WOBBLY CHICKEN, METAL",1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
131991,547651,22291,HANGING CHICK CREAM DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
131992,547651,22248,DECORATION PINK CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131995,547651,22595,GINGHAM HEART DECORATION,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131996,547651,22249,DECORATION WHITE CHICK MAGIC GARDEN,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131997,547651,22288,HANGING METAL RABBIT DECORATION,1,2011-03-24 12:11:00,1.25,16904.0,United Kingdom
131998,547651,22595,GINGHAM HEART DECORATION,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
131999,547651,85203,HANGING WOOD AND FELT BUTTERFLY,1,2011-03-24 12:11:00,0.42,16904.0,United Kingdom
132000,547651,84457,SET/3 RABBITS FLOWER SKIPPPING ROPE,1,2011-03-24 12:11:00,0.85,16904.0,United Kingdom
132001,547651,22293,HANGING CHICK GREEN DECORATION,1,2011-03-24 12:11:00,1.45,16904.0,United Kingdom
132003,547651,22285,HANGING HEN ON NEST DECORATION,1,2011-03-24 12:11:00,1.65,16904.0,United Kingdom
132017,547651,22431,WATERING CAN BLUE ELEPHANT,1,2011-03-24 12:11:00,1.95,16904.0,United Kingdom
132019,547651,22431,WATERING CAN BLUE ELEPHANT,1,2011-03-24 12:11:00,1.95,16904.0,United Kingdom